### ISSUE TITLE
Generate button not working after generating several images with txt2img

### ISSUE THREAD

**Issue by MinionTim** [wibus-wee/stable_diffusion_chilloutmix_ipynb#19] opened 2023-04-15 03:28 UTC
### Describe the bug

with the latest code **stable_diffusion_1_5_webui.ipynb** at [b8d8ea7](https://github.com/wibus-wee/stable-diffusion-webui-ipynb/commit/b8d8ea73c33876ddf6d2dbb7af9ada5429e101ae)，i use checkpoint of **chilloutmix_NiPrunedFp32Fix.safetensors [fc2511737a]**, genrate some images with txt2img by promts from **prompts.md** file。

it works at the first few time，then genertate stop work, and there's no more logs at colab backend when click generate button. I have to restart colab runtime，then works again . But it still appears like i said before.

### Reproduction

install steps by [选择模型] - [检查 GPU & 检查环境] - [ 第一次使用 - 安装依赖并启动]  -> input prompts --> generate

### System Info

```Shell
python: 3.9.16  •  
torch: 1.13.1+cu116  •  
xformers: 0.0.16  •  
gradio: 3.23.0  •  
commit: 22bcc7be  •  
checkpoint: fc2511737a
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wibus-wee** [comment] 2023-04-15 04:46
It seems that this notebook is not the cause of the issue. Maybe you can enable the "Clareflared" option in Step 3. 

Please refer to https://github.com/wibus-wee/stable-diffusion-webui-ipynb/wiki/WebUI#about-step-4 for more information.

**Comment by MinionTim** [comment] 2023-04-15 06:03
maybe not. it works when i turn to generate with img2img，but txt2img is still not ok until i restart colab runtime.
i'll try your sugguest later...my google colab is down due to free limitation a second ago。。。

**Comment by wibus-wee** [comment] 2023-04-15 06:35
a bit strange. i have not encountered such a situation, did you encounter this problem after retry to refresh the page? and is it available again after refreshing?

**Comment by MinionTim** [comment] 2023-05-12 09:54
it seems a litter better after reinstall all scripts. -_-!

**Comment by wibus-wee** [comment] 2023-05-21 02:53
ok 👌, so I will close the issue, and you can create a new issue if you still have problems

**Closed as completed** 2023-05-21 02:53 UTC
Labels: question
